name: Docker Image CI

on:
  push:
    branches: 
      - main

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
       working-directory: fastapi_lambda_api-gateway_sample 
      
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag python-fast-api:$(date +%s)
