name: Build and Push to ECR
on:
 push:
   branches:
     - main  # or your desired branch
env:
 AWS_REGION: us-east-1  # Change to your AWS region
 ECR_REPO: anita
jobs:
 build-and-push:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout code
     uses: actions/checkout@v2
   - name: Login to AWS ECR
     id: login-ecr
     uses: aws-actions/amazon-ecr-login@v1
   - name: Build, tag, and push Docker image
     id: build-and-push-image
     env:
       ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
       ECR_REPO: ${{ env.ECR_REPO }}
       IMAGE_TAG: ${{ github.sha }}
     run: |
       docker build -t $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG .
       docker push $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
   - name: Store image URI as an output
     id: set-output
     run: echo "::set-output name=image_uri::$ECR_REGISTRY/$ECR_REPO:${{ github.sha }}"
